/**
 * funcdock create <name> — Create a new function template
 */

import fs from 'fs/promises';
import path from 'path';
import { projectRoot, log, colors, validateFunctionName } from '../utils.js';

export const name = 'create';
export const description = 'Create a new function template';

const HANDLER_TEMPLATE = (name) => `/**
 * ${name} Function
 * Generated by FuncDock
 */

export default async function handler(req, res) {
  const { method, query, body, logger } = req;

  logger.info(\`Request received: \${method} \${req.routePath}\`);

  switch (method) {
    case 'GET': {
      return res.status(200).json({
        message: 'GET request successful',
        function: '${name}',
        query,
        timestamp: new Date().toISOString(),
      });
    }

    case 'POST': {
      if (!body || Object.keys(body).length === 0) {
        return res.status(400).json({
          error: 'Bad Request',
          message: 'Request body is required',
        });
      }
      return res.status(201).json({
        message: 'Resource created',
        function: '${name}',
        data: body,
        timestamp: new Date().toISOString(),
      });
    }

    case 'PUT': {
      return res.status(200).json({
        message: 'Resource updated',
        function: '${name}',
        data: body,
        timestamp: new Date().toISOString(),
      });
    }

    case 'DELETE': {
      return res.status(200).json({
        message: 'Resource deleted',
        function: '${name}',
        timestamp: new Date().toISOString(),
      });
    }

    default:
      return res.status(405).json({
        error: 'Method Not Allowed',
        method,
        supportedMethods: ['GET', 'POST', 'PUT', 'DELETE'],
      });
  }
}
`;

const TEST_TEMPLATE = (name) => `import { testHandler, expectStatus } from '../../test/setup.mjs';
import handler from './handler.js';

describe('${name}', () => {
  it('should respond to GET', async () => {
    const { data } = await testHandler(handler, { method: 'GET' });
    expect(data.message).toBe('GET request successful');
    expect(data.function).toBe('${name}');
  });

  it('should respond to POST', async () => {
    const { data } = await testHandler(handler, {
      method: 'POST',
      body: { name: 'test' },
    });
    expect(data.message).toBe('Resource created');
    expect(data.data).toEqual({ name: 'test' });
  });

  it('should reject empty POST body', async () => {
    const { statusCode } = await testHandler(handler, { method: 'POST', body: {} });
    expect(statusCode).toBe(400);
  });

  it('should reject unsupported methods', async () => {
    const { statusCode } = await testHandler(handler, { method: 'PATCH' });
    expect(statusCode).toBe(405);
  });
});
`;

const ROUTE_CONFIG = (name) => ({
  base: `/${name}`,
  handler: 'handler.js',
  routes: [{ path: '/', methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'] }],
});

const PACKAGE_JSON = (name) => ({
  name: `${name}-function`,
  version: '1.0.0',
  description: `${name} serverless function for FuncDock`,
  main: 'handler.js',
  type: 'module',
  keywords: ['funcdock', 'serverless', 'function', name],
  dependencies: {},
});

const README_TEMPLATE = (name) => `# ${name}

FuncDock serverless function.

## Files

- \`handler.js\` — Main request handler
- \`handler.test.mjs\` — Jest tests
- \`route.config.json\` — Route configuration
- \`package.json\` — Function dependencies

## Testing

\`\`\`bash
funcdock test ${name}
\`\`\`

## Deployment

\`\`\`bash
funcdock deploy --local ./functions/${name} --name ${name}
\`\`\`
`;

export async function run(args) {
  const [name] = args.filter((a) => !a.startsWith('-'));

  if (!name || args.includes('--help') || args.includes('-h')) {
    log(`\n${colors.cyan}funcdock create <name>${colors.reset}\n`, 'reset');
    log('Scaffold a new FuncDock function with handler, tests, and config.\n', 'gray');
    log('Usage: funcdock create <function-name>\n', 'yellow');
    log('Example: funcdock create payment-api\n', 'gray');
    return;
  }

  if (!validateFunctionName(name)) {
    log(
      `${colors.red}Invalid function name: "${name}". Use only letters, numbers, hyphens, and underscores.${colors.reset}`,
      'reset'
    );
    process.exit(2);
  }

  const functionsDir = path.join(projectRoot, 'functions');
  const funcDir = path.join(functionsDir, name);

  try {
    await fs.access(funcDir);
    log(`${colors.red}Function "${name}" already exists.${colors.reset}`, 'reset');
    process.exit(1);
  } catch {
    // doesn't exist, good
  }

  log(`📁 Creating function template: ${name}`, 'blue');

  await fs.mkdir(funcDir, { recursive: true });

  await fs.writeFile(path.join(funcDir, 'handler.js'), HANDLER_TEMPLATE(name));
  log(`  ✅ handler.js`, 'green');

  await fs.writeFile(path.join(funcDir, 'handler.test.mjs'), TEST_TEMPLATE(name));
  log(`  ✅ handler.test.mjs`, 'green');

  await fs.writeFile(
    path.join(funcDir, 'route.config.json'),
    JSON.stringify(ROUTE_CONFIG(name), null, 2)
  );
  log(`  ✅ route.config.json`, 'green');

  await fs.writeFile(
    path.join(funcDir, 'package.json'),
    JSON.stringify(PACKAGE_JSON(name), null, 2)
  );
  log(`  ✅ package.json`, 'green');

  await fs.writeFile(path.join(funcDir, 'README.md'), README_TEMPLATE(name));
  log(`  ✅ README.md`, 'green');

  log(`\n${colors.green}Function "${name}" created in functions/${name}/${colors.reset}`, 'reset');
  log(`Run tests:   funcdock test ${name}`, 'gray');
  log(`Deploy:      funcdock deploy --local ./functions/${name} --name ${name}\n`, 'gray');
}
